### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by amritsinghbains** [bassaer/ChatMessageView#1]
FATAL EXCEPTION: main
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageBitmap(android.graphics.Bitmap)' on a null object reference
                                                                                   at jp.bassaer.chatmessageview.MessageAdapter.getView(MessageAdapter.java:52)
                                                                                   at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                   at android.widget.ListView.makeAndAddView(ListView.java:1876)
                                                                                   at android.widget.ListView.fillUp(ListView.java:736)
                                                                                   at android.widget.ListView.fillGap(ListView.java:675)
                                                                                   at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
                                                                                   at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3448)
                                                                                   at android.widget.AbsListView.onTouchMove(AbsListView.java:3844)
                                                                                   at android.widget.AbsListView.onTouchEvent(AbsListView.java:3675)
                                                                                   at android.view.View.dispatchTouchEvent(View.java:9323)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2707)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2713)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2414)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2409)
                                                                                   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2370)
                                                                                   at android.view.View.dispatchPointerEvent(View.java:9599)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4298)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4142)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3814)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3871)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6510)
                                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6454)
                                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6415)
                                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6643)
                                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6611)

**Comment by bassaer** [comment]
Hi @amritsinghbains ,
Sorry for late reply. Fixed this issue.
Please update 1.2.0, if still necessary. 

Thanks.
