### ISSUE TITLE
Library Click Events not being triggered [2]

### ISSUE THREAD

**Issue by arthurabreu** [bassaer/ChatMessageView#119]
Hi,

I have a ChatView where I want the user to be able to click on the bubble and get something done.

Currently what happens is, on the first time I open my Fragment which contains the ChatView and click on any bubble, nothing happens.

After I go back to the previous Fragment (A list of chats like WhatsApp main screen) and open the same chat I was previously and click on the **same** bubble or _any other_, the bubble click works.

My code:
```
chatView.setOnBubbleClickListener(new Message.OnBubbleClickListener() {

               @Override

                    public void onClick(Message message) {

                              if (CheckNetworkAvailability.isNetworkAvailable(getContext())){

                                     presenter.onBubbleClicked(message);

                                     Toast.makeText(getContext(), "Bubble Clicked", Toast.LENGTH_SHORT).show();

                               }else{

                                       Toast.makeText(getContext(), "Can't open message", Toast.LENGTH_SHORT).show();

                }
            }
        });
```

(**_Not important but for context:_** This code of mine checks if there is internet available and if there is it uses the content from the API I'm using to open a WebView from the clicked message)

**IMPORTANT:**
_Code I've used to make tests:_

```
chatView.setOnBubbleClickListener(new Message.OnBubbleClickListener() {
            @Override
            public void onClick(Message message) {

                 Toast.makeText(getContext(), "Bubble Clicked", Toast.LENGTH_SHORT).show();
              
            }
        });
```

Both codes present the behaviour I've mentioned. At first nothing happens, after coming back to the ChatView activity the BubbleClick works. I can't figure out why.

**Comment by arthurabreu** [comment]
After updating the library to the latest version, i get this error on the first time I use the on click listener:

`01-29 15:43:06.122 16582-16582/com.af2g.treinus E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.af2g.treinus, PID: 16582
                                                                  kotlin.UninitializedPropertyAccessException: lateinit property bubbleClickListener has not been initialized
                                                                      at com.github.bassaer.chatmessageview.view.MessageAdapter.access$getBubbleClickListener$p(MessageAdapter.kt:30)
                                                                      at com.github.bassaer.chatmessageview.view.MessageAdapter$getView$13.onClick(MessageAdapter.kt:236)
                                                                      at android.view.View.performClick(View.java:5637)
                                                                      at android.view.View$PerformClick.run(View.java:22429)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

My code:

`chatView.setOnBubbleClickListener(new Message.OnBubbleClickListener() {
            @Override
            public void onClick(Message message) {
                if (CheckNetworkAvailability.isNetworkAvailable(getContext())){
                    presenter.onBubbleClicked(message); (MVP architeture, send the message to my presenter, nothing unusual)
                }else{
                    Toast.makeText(getContext(), "Error", Toast.LENGTH_SHORT).show();
                }
            }
        });`
