### ISSUE TITLE
 kotlin.UninitializedPropertyAccessException: lateinit property bubbleClickListener has not been initialized

### ISSUE THREAD

**Issue by arthurabreu** [bassaer/ChatMessageView#126]
After updating the library to the latest version, i get this error on the first time I use the on click listener:

```
01-29 15:43:06.122 16582-16582/com.myapp E/AndroidRuntime: 
FATAL EXCEPTION: main Process: com.myapp, PID: 16582 
kotlin.UninitializedPropertyAccessException: lateinit property bubbleClickListener has not been initialized
at com.github.bassaer.chatmessageview.view.MessageAdapter.access$getBubbleClickListener$p(MessageAdapter.kt:30)
at com.github.bassaer.chatmessageview.view.MessageAdapter$getView$13.onClick(MessageAdapter.kt:236) 
at android.view.View.performClick(View.java:5637) 
at android.view.View$PerformClick.run(View.java:22429)
at android.os.Handler.handleCallback(Handler.java:751) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

My code:

```
chatView.setOnBubbleClickListener(new Message.OnBubbleClickListener() { 
  @Override 
  public void onClick(Message message) {
     if (CheckNetworkAvailability.isNetworkAvailable(getContext())){ 
       presenter.onBubbleClicked(message);
       (MVP architeture, send the message to my presenter, nothing unusual) 
      }else{ 
       Toast.makeText(getContext(), "Error", Toast.LENGTH_SHORT).show();
      }   
    } 
});
```

**Comment by bassaer** [comment]
Thanks. let me check.

**Comment by bassaer** [comment]
please update version 1.8.8
Thanks.

**Comment by rital-naik-adrosonic** [comment]
am **unable to add version 2.1.0** so  I have added version 2.0.1. However even then am not able to call bubbleClickListener. 
Below is my code:
 var listener = object: Message.OnBubbleClickListener{
            override fun onClick(message: Message) {
                Log.e("Test","OnBubbleClickListener")
            }
        }
        mBinding?.chatView?.setOnBubbleClickListener(listener)
