### ISSUE TITLE
unable to set option menu

### ISSUE THREAD

**Issue by RanchhodRamani** [bassaer/ChatMessageView#129]
mChatView.setOptionIcon(R.drawable.ic_action_add);

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageDrawable(android.graphics.drawable.Drawable)' on a null object reference
                                                                          at com.github.bassaer.chatmessageview.view.ChatView.setOptionButtonColor(ChatView.kt:172)
                                                                          at com.github.bassaer.chatmessageview.view.ChatView.setOptionIcon(ChatView.kt:190)
                                                                          at app.pertemps.workforce.ChatActivity.onCreate(ChatActivity.java:51)

**Comment by bassaer** [comment]
which version do you use?

**Comment by durac** [comment]
I have the same problem unfortunately. I am using version 1.11.2
