### ISSUE TITLE
Error for missing attribute using version 1.11.1

### ISSUE THREAD

**Issue by Adsama94** [bassaer/ChatMessageView#154]
If I put the following line in my app level build.gradle file I get the following error - 

`Java Compiler - `
`error: failed linking file resources.`

`Android issues - `
`error:attribute 'my_package_name:civ_fill_color' not found'`

If I click on the above issue I get redirected to the `user_icon_right.xml` which contains the `CircleImageView` layout attributes and there you can also see the `app:civ_fillColor` attribute.

To fix this, simply revert back to 1.11.0 and the error goes away and the library works perfectly.

**Comment by bassaer** [comment]
@Adsama94 
Thanks for letting me know 👍 
please try updating version 1.11.2

**Comment by Adsama94** [comment]
I'm still getting an error after updating to version 1.11.2

Here's my log - 

```
07-16 10:37:04.642 9023-9023/com.walkinapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.walkinapp, PID: 9023
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.walkinapp/com.walkinapp.activities.ChatActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.github.bassaer.chatmessageview.view.ChatView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2493)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576)
        at android.app.ActivityThread.access$1000(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.github.bassaer.chatmessageview.view.ChatView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:395)
        at android.app.Activity.setContentView(Activity.java:2181)
        at com.walkinapp.activities.ChatActivity.onCreate(ChatActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:6289)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.github.bassaer.chatmessageview.view.ChatView
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:395) 
        at android.app.Activity.setContentView(Activity.java:2181) 
        at com.walkinapp.activities.ChatActivity.onCreate(ChatActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:6289) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:395) 
        at android.app.Activity.setContentView(Activity.java:2181) 
        at com.walkinapp.activities.ChatActivity.onCreate(ChatActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:6289) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.github.bassaer.chatmessageview.view.ChatView.<init>(ChatView.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:395) 
        at android.app.Activity.setContentView(Activity.java:2181) 
        at com.walkinapp.activities.ChatActivity.onCreate(ChatActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:6289) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.walkinapp-1/base.apk", zip file "/data/app/com.walkinapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.walkinapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.walkinapp-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.github.bassaer.chatmessageview.view.ChatView.<init>(ChatView.kt) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:395) 
        at android.app.Activity.setContentView(Activity.java:2181) 
        at com.walkinapp.activities.ChatActivity.onCreate(ChatActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:6289) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.lang.Class.classForName(Native Method)
    		at java.lang.Boot

```
