### ISSUE TITLE
java.lang.NullPointerException Using ChatView in Fragment

### ISSUE THREAD

**Issue by maherzaidoune** [bassaer/ChatMessageView#64]
i got NullPointer Exception when i try to write a 2nd message using Chat view on Fragment
this is my Logcat

FATAL EXCEPTION: main
                                                        Process: rrdl.crt, PID: 1636
                                                        java.lang.NullPointerException
                                                            at com.github.bassaer.chatmessageview.views.adapters.MessageAdapter.getView(MessageAdapter.java:350)
                                                            at android.widget.AbsListView.obtainView(AbsListView.java:2338)
                                                            at android.widget.ListView.makeAndAddView(ListView.java:1812)
                                                            at android.widget.ListView.fillDown(ListView.java:698)
                                                            at android.widget.ListView.fillGap(ListView.java:662)
                                                            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5529)
                                                            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4596)
                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                            at android.view.Choreographer.doFrame(Choreographer.java:559)
                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                            at android.os.Looper.loop(Looper.java:193)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by maherzaidoune** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextSize(int, float)' on a null object reference

**Comment by bassaer** [comment]
@maherzaidoune 
please update version 1.5.3
Thanks

**Comment by maherzaidoune** [comment]
thank you it's working fine now
